# Generated by Django 4.2.7 on 2024-09-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thongbao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chap', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Truyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('theloai', models.TextField()),
                ('mota', models.TextField()),
                ('tacgia', models.CharField(max_length=255)),
                ('luotthich', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Nguoidung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('matkhau', models.CharField(max_length=255)),
                ('vaitro', models.CharField(max_length=255)),
                ('lichsu', models.ManyToManyField(related_name='lichsu', to='myapp.truyen')),
                ('thongbao', models.ManyToManyField(related_name='thongbao', to='myapp.thongbao')),
                ('truyendang', models.ManyToManyField(related_name='truyendang', to='myapp.truyen')),
                ('yeuthich', models.ManyToManyField(related_name='yeuthich', to='myapp.truyen')),
            ],
        ),
        migrations.CreateModel(
            name='Chap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('luotxem', models.CharField(max_length=255)),
                ('thoigiandang', models.DateTimeField(auto_now_add=True)),
                ('Truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chap', to='myapp.truyen')),
            ],
        ),
    ]
