# Generated by Django 4.2.7 on 2024-09-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chap',
            name='luotxem',
            field=models.BigIntegerField(default=0),
        ),
    ]
