# Generated by Django 4.2.7 on 2024-10-03 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_chap_luotxem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thongbao',
            old_name='chap',
            new_name='noidung',
        ),
        migrations.RemoveField(
            model_name='chap',
            name='Truyen',
        ),
        migrations.AddField(
            model_name='chap',
            name='stt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='truyen',
            name='anhbia',
            field=models.FileField(blank=True, upload_to='anhbia/'),
        ),
        migrations.AddField(
            model_name='truyen',
            name='anhnen',
            field=models.FileField(blank=True, upload_to='anhnen/'),
        ),
        migrations.CreateModel(
            name='Trang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anh', models.FileField(upload_to='anhchap/')),
                ('chap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chap', to='myapp.truyen')),
            ],
        ),
        migrations.AddField(
            model_name='chap',
            name='truyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truyen', to='myapp.truyen'),
        ),
    ]
