# Generated by Django 4.2.7 on 2024-10-03 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_chap_thongbao_noidung_remove_chap_truyen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chap',
            name='truyen',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truyen', to='myapp.truyen'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='lichsu',
            field=models.ManyToManyField(default=0, related_name='lichsu', to='myapp.truyen'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='thongbao',
            field=models.ManyToManyField(default=0, related_name='thongbao', to='myapp.thongbao'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='truyendang',
            field=models.ManyToManyField(default=0, related_name='truyendang', to='myapp.truyen'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='yeuthich',
            field=models.ManyToManyField(default=0, related_name='yeuthich', to='myapp.truyen'),
        ),
        migrations.AlterField(
            model_name='trang',
            name='chap',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chap', to='myapp.truyen'),
        ),
    ]
