# Generated by Django 4.2.7 on 2024-10-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_chap_truyen_alter_nguoidung_lichsu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trang',
            name='chap',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chap', to='myapp.chap'),
        ),
    ]
