# Generated by Django 4.2.7 on 2024-10-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_nguoidung_lichsu_alter_nguoidung_thongbao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='lichsu',
            field=models.ManyToManyField(blank=True, default=0, related_name='lichsu', to='myapp.truyen'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='thongbao',
            field=models.ManyToManyField(blank=True, default=0, related_name='thongbao', to='myapp.thongbao'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='truyendang',
            field=models.ManyToManyField(blank=True, related_name='truyendang', to='myapp.truyen'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='yeuthich',
            field=models.ManyToManyField(blank=True, default=0, related_name='yeuthich', to='myapp.truyen'),
        ),
    ]
