# Generated by Django 4.2.7 on 2024-10-03 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_nguoidung_lichsu_alter_nguoidung_thongbao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chap',
            name='truyen',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chap', to='myapp.truyen'),
        ),
    ]
