# Generated by Django 4.2.7 on 2024-10-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_thongbao_theloai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongbao',
            name='theloai',
            field=models.CharField(default='Thông báo mới!!', max_length=255),
        ),
    ]
